import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type ThemeMode = 'light' | 'dark';
export type AppLanguage = 'en' | 'ru' | 'uz';

interface ThemeLanguageContextValue {
  theme: ThemeMode;
  language: AppLanguage;
  setTheme: (theme: ThemeMode) => void;
  setLanguage: (language: AppLanguage) => void;
  t: (key: string) => string;
}

const ThemeLanguageContext = createContext<ThemeLanguageContextValue | undefined>(undefined);

const translations: Record<AppLanguage, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.courses': 'Courses',
    'nav.teachers': 'Teachers',
    'nav.results': 'Results',
    'nav.gallery': 'Gallery',
    'nav.news': 'News',
    'nav.testimonials': 'Testimonials',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.levelTest': 'Level Test',
    'nav.enroll': 'Enroll Now',
    'nav.admin': 'Admin Panel',
    'nav.mobileAdmin': 'Admin',
    'nav.mobileLevelTest': 'Take Free English Level Test',
    'nav.mobileEnroll': 'Enroll Now',
    'nav.mobileAdminGo': 'Go to Admin Panel',
    'hero.tag': 'Premier International Education Center',
    'hero.title': 'Build Your Future with',
    'hero.titleHighlight': 'iStudy Academy.',
    'hero.subtitle': 'Master English, IELTS, CEFR, SAT and professional tech & design skills with Cambridge certified native teachers and top examiners.',
    'hero.enroll': 'Enroll Now',
    'hero.levelTest': 'Take Level Test',
    'hero.trust1': 'Cambridge Standard',
    'hero.trust2': 'Score Band Guarantee',
    'hero.trust3': 'Small Interactive Groups',
    'hero.stats.students': 'Successful Students',
    'hero.stats.successRate': 'Exam Success Rate',
    'hero.stats.teachers': 'Expert Teachers',
    'hero.stats.courses': 'Specialized Courses',
    'hero.stats.excellence': 'Academic Excellence',
    'hero.card.title': 'Student Achievements',
    'hero.card.subtitle': 'Official Results Database',
    'hero.card.badge': 'Live Verified',
    'hero.card.video': 'Watch Academy Campus Video Tour',
    'hero.noResults.title': 'Top Exam Results & International Admissions',
    'hero.noResults.desc': 'Student success records live in Supabase database.',
    'about.tag': 'About iStudy Academy',
    'about.title': 'Where Ambition Meets',
    'about.titleHighlight': 'World-Class Mentorship.',
    'about.subtitle': 'We do not just teach courses; we build structured pathways to top university admissions and high-paying global careers.',
    'about.tabs.story': 'Story',
    'about.tabs.mission': 'Mission',
    'about.tabs.vision': 'Vision',
    'about.tabs.methodology': 'Methodology',
    'about.story.title': 'Founded on Excellence & Genuine Results',
    'about.story.description': 'iStudy Academy was established with a singular mission: to provide world-class international education without compromise. Over the past 3+ years, we have grown into a multi-discipline academy with thousands of successful graduates studying across global universities and leading tech firms.',
    'about.story.point1': 'Proprietary score-boosting methodology tested on 5,000+ candidates',
    'about.story.point2': 'Official test simulation center replicating real exam stress',
    'about.story.point3': 'Cambridge CELTA & DELTA certified department heads',
    'about.mission.title': 'Empowering Students to Reach Global Heights',
    'about.mission.description': 'Our mission is to equip every ambitious learner with high-value international qualifications (IELTS, CEFR, SAT) and future-proof digital skills (Software Engineering, UI/UX, SMM) that open doors to global university grants and top careers.',
    'about.mission.point1': 'Democratizing access to high-band IELTS and SAT scores',
    'about.mission.point2': 'Fostering critical thinking, presentation confidence, and fluency',
    'about.mission.point3': 'Providing 100% transparent tracking for parents and candidates',
    'about.vision.title': 'Becoming Central Asia’s #1 Prep & Tech Gateway',
    'about.vision.description': 'We envision a future where iStudy Academy stands as the benchmark for educational excellence across the region — recognized globally for sending thousands of scholars to top-tier universities every academic year.',
    'about.vision.point1': 'Continuous integration of AI tools in student diagnostics',
    'about.vision.point2': 'Expanding strategic partnerships with foreign universities',
    'about.vision.point3': 'Building a lifelong alumni network of leaders and innovators',
    'about.methodology.title': 'The 4-Pillar iStudy Learning Framework',
    'about.methodology.description': 'Unlike standard passive lectures, our methodology centers on active production: 40% concept foundation, 30% intense real-time drills, 20% mock examination testing, and 10% 1-on-1 examiner feedback.',
    'about.methodology.point1': 'Small interactive cohorts limited to 10-12 students max',
    'about.methodology.point2': 'Personalized weak-spot error log analysis after every test',
    'about.methodology.point3': 'Daily speaking clubs and project-based code reviews',
    'about.card.title': 'iStudy Academy Modern Campus',
    'about.card.subtitle': 'High-tech interactive classrooms & IELTS testing labs.',
    'about.card.badge': 'Video Tour',
    'about.card.branch': 'Explore Our Main Campus',
    'about.card.branchSubtitle': 'Central Branch • Campus Tour',
    'about.feature1.title': 'Cambridge Certified',
    'about.feature1.subtitle': 'Licensed Standard',
    'about.feature2.title': 'Score Guarantee',
    'about.feature2.subtitle': 'Band 7.0+ Target',
    'why.tag': 'The iStudy Advantage',
    'why.title': 'Why Top Students Choose',
    'why.titleHighlight': 'iStudy Academy.',
    'why.subtitle': 'Every detail of our academic system is engineered to maximize your score, build real confidence, and guarantee results.',
    'why.feature.standard': 'Standard Feature',
    'courses.tag': 'Academic Programs',
    'courses.title': 'Explore Premium',
    'courses.titleHighlight': 'Educational Courses.',
    'courses.subtitle': 'Real courses powered directly by Supabase cloud database.',
    'courses.filter.all': 'All Courses',
    'courses.filter.english': 'English & Exams (IELTS/CEFR)',
    'courses.filter.prep': 'SAT & Math Prep',
    'courses.filter.tech': 'Programming & AI',
    'courses.filter.design': 'Graphic Design & SMM',
    'courses.search': 'Search courses...',
    'courses.empty.title': 'No Courses in Supabase Database',
    'courses.empty.desc': 'All mock data has been removed. Create and manage live courses directly in your Admin Panel.',
    'courses.empty.admin': 'Go to Admin Panel',
    'courses.empty.enroll': 'Quick Enroll',
    'courses.noMatch.title': 'No courses match your filter',
    'courses.noMatch.desc': 'Try resetting your search query or selecting another category.',
    'courses.reset': 'Reset Filters',
    'courses.card.level': 'Level',
    'courses.card.learnMore': 'Learn More',
    'courses.card.enroll': 'Enroll Now',
    'teachers.tag': 'World-Class Mentors',
    'teachers.title': 'Learn From Certified',
    'teachers.titleHighlight': 'Examiners & Experts.',
    'teachers.subtitle': 'Our faculty includes Cambridge CELTA/DELTA native instructors, Band 9 holders, and industry senior developers.',
    'teachers.credentials': 'Certifications & Credentials:',
    'teachers.book': 'Book Consult',
    'teachers.exp': 'Exp',
    'results.tag': 'Student Hall of Fame',
    'results.title': 'Real Student Results &',
    'results.titleHighlight': 'University Admissions.',
    'results.subtitle': 'See how our candidates transformed their scores and unlocked global scholarship opportunities.',
    'results.growth': 'Score Growth:',
    'gallery.tag': 'Campus & Events',
    'gallery.title': 'Life at iStudy',
    'gallery.titleHighlight': 'Academy Gallery.',
    'gallery.subtitle': 'Take a look inside our high-tech study hubs, annual graduation galas, and energetic speaking clubs.',
    'gallery.filter.all': 'All Photos & Videos',
    'gallery.filter.classrooms': 'Classrooms',
    'gallery.filter.graduation': 'Graduation',
    'gallery.filter.events': 'Events & Masterclasses',
    'gallery.filter.activities': 'Student Life',
    'testimonials.tag': 'Student & Parent Reviews',
    'testimonials.title': 'Loved by Over',
    'testimonials.titleHighlight': '5,000+ Families.',
    'testimonials.subtitle': 'Read authentic feedback from students who hit Band 8.5+ and parents who watched their children thrive.',
    'testimonials.filter.all': 'All Reviews',
    'testimonials.filter.student': 'Student Reviews',
    'testimonials.filter.parent': 'Parent Reviews',
    'testimonials.filter.alumni': 'Alumni Reviews',
    'news.tag': 'Latest News & Events',
    'news.title': 'Stay Updated with',
    'news.titleHighlight': 'iStudy Academy News.',
    'news.subtitle': 'Discover upcoming free mock exams, university admission webinars, and academic workshops.',
    'news.readMore': 'Read Full Article',
    'faq.tag': 'Frequently Asked Questions',
    'faq.title': 'Have Questions?',
    'faq.titleHighlight': 'We Have Answers.',
    'faq.subtitle': 'Find everything you need to know about placement tests, timetables, and score guarantees.',
    'faq.search': 'Search FAQ questions...',
    'faq.category.all': 'All',
    'faq.category.general': 'General',
    'faq.category.courses': 'Courses',
    'faq.category.payments': 'Payments',
    'faq.category.schedule': 'Schedule',
    'contact.tag': 'Contact & Locations',
    'contact.title': 'Visit Our Campuses or',
    'contact.titleHighlight': 'Request a Free Consultation.',
    'contact.subtitle': 'Our admissions office is open Monday through Saturday. Fill out the form below or drop by any of our 3 central campuses.',
    'contact.branchTitle': 'Select Academy Branch:',
    'contact.activeBranch': 'Active Branch',
    'contact.socialTitle': 'Follow iStudy Official:',
    'contact.formTitle': 'Send Us a Message / Enroll',
    'contact.formSubtitle': 'Leave your details and our education manager will call you back within 15 minutes!',
    'contact.name': 'Full Name *',
    'contact.phone': 'Phone Number *',
    'contact.course': 'Select Course',
    'contact.branch': 'Select Branch',
    'contact.message': 'Message or Questions (Optional)',
    'contact.messagePlaceholder': 'Tell us about your target score or preferred timetable...',
    'contact.social.telegram': 'Telegram',
    'contact.social.instagram': 'Instagram',
    'contact.social.facebook': 'Facebook',
    'contact.social.linkedin': 'LinkedIn',
    'contact.exampleName': 'e.g., John Doe',
    'contact.submit': 'Submit Request & Get Consultation',
    'contact.sending': 'Sending Request...',
    'footer.subscribeTitle': 'Subscribe for Free Mock Exam Alerts & Study Tips',
    'footer.subscribeSubtitle': 'Get weekly IELTS vocabulary sheets and university scholarship news straight to your inbox.',
    'footer.emailPlaceholder': 'Enter your email...',
    'footer.subscribe': 'Subscribe',
    'footer.quickLinks': 'Quick Links',
    'footer.aboutUs': 'About Us',
    'footer.allCourses': 'All Courses',
    'footer.faculty': 'Faculty & Mentors',
    'footer.studentResults': 'Student Results',
    'footer.photoGallery': 'Photo Gallery',
    'footer.newsEvents': 'News & Events',
    'footer.programs': 'Academic Programs',
    'footer.campuses': 'Campuses',
    'footer.privacy': 'Privacy Policy & Terms',
    'footer.backTop': 'Back to Top',
    'footer.copyright': '© 2026 iStudy Academy. All rights reserved. International Licensed Educational Center.',
    'toast.enrollSuccess.title': 'Registration Confirmed!',
    'toast.enrollSuccess.desc': 'Thank you {name}. Your seat for "{course}" is reserved! Ref: {ref}',
    'toast.contactSuccess.title': 'Request Received!',
    'toast.contactSuccess.desc': 'Dear {name}, our education manager will call {phone} back within 15 minutes.',
    'toast.subscribeSuccess.title': 'Subscribed to iStudy Newsletter!',
    'toast.subscribeSuccess.desc': 'We sent a confirmation link to {email}. Check your inbox for free IELTS prep materials.',
    'toast.consultation.title': 'Consultation Request with {teacher}',
    'toast.consultation.desc': 'Please fill in the quick contact form below or call +998 (71) 200-77-88 to schedule.',
    'toast.error.title': 'Request Failed',
    'toast.error.desc': 'Unable to save your message right now. Please try again later.',
    'toast.subscribeError.title': 'Subscription Failed',
    'toast.subscribeError.desc': 'Unable to subscribe your email at this time. Please try again later.',
    'why.feature1.title': 'Experienced Teachers',
    'why.feature1.desc': 'Cambridge CELTA & DELTA certified instructors, native speakers, and IELTS Band 9.0 holders.',
    'why.feature2.title': 'Modern Classrooms',
    'why.feature2.desc': 'Interactive digital boards, iMac tech labs, comfortable ergonomic seating, and silent study hubs.',
    'why.feature3.title': 'International Curriculum',
    'why.feature3.desc': 'Officially licensed Cambridge, Oxford, and College Board SAT digital study frameworks.',
    'why.feature4.title': 'Small Study Groups',
    'why.feature4.desc': 'Strictly limited to 10 - 12 students per class ensuring personal feedback and speaking time.',
    'why.feature5.title': 'Flexible Schedule',
    'why.feature5.desc': 'Choose from Morning (09:00), Afternoon (14:30), Evening (18:30), or Weekend Intensive shifts.',
    'why.feature6.title': 'Affordable Prices',
    'why.feature6.desc': 'Transparent pricing with no hidden fees, sibling discounts, and 3-month upfront savings.',
    'why.feature7.title': 'Official Certificates',
    'why.feature7.desc': 'Graduation diplomas with unique QR verification recognized by employers and institutions.',
    'why.feature8.title': 'Career & Admissions Help',
    'why.feature8.desc': 'Dedicated advisors to assist with Common App, motivation letters, and full scholarships.',
    'common.themeLight': 'Light',
    'common.themeDark': 'Dark',
    'common.language': 'Language',
    'common.languageEn': 'English',
    'common.languageRu': 'Русский',
    'common.languageUz': 'O‘zbek',
    'common.selectLanguage': 'Select language',
    'common.changeTheme': 'Theme',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.about': 'О нас',
    'nav.courses': 'Курсы',
    'nav.teachers': 'Преподаватели',
    'nav.results': 'Результаты',
    'nav.gallery': 'Галерея',
    'nav.news': 'Новости',
    'nav.testimonials': 'Отзывы',
    'nav.faq': 'FAQ',
    'nav.contact': 'Контакты',
    'nav.levelTest': 'Тест уровня',
    'nav.enroll': 'Записаться',
    'nav.admin': 'Панель админа',
    'nav.mobileAdmin': 'Админ',
    'nav.mobileLevelTest': 'Пройди бесплатный тест уровня',
    'nav.mobileEnroll': 'Записаться',
    'nav.mobileAdminGo': 'Перейти в админ-панель',
    'hero.tag': 'Премиальный международный образовательный центр',
    'hero.title': 'Построй своё будущее вместе с',
    'hero.titleHighlight': 'iStudy Academy.',
    'hero.subtitle': 'Освой английский, IELTS, CEFR, SAT и современные навыки в технологиях и дизайне вместе с сертифицированными преподавателями и экспертами по экзаменам.',
    'hero.enroll': 'Записаться',
    'hero.levelTest': 'Пройти тест',
    'hero.trust1': 'Стандарт Cambridge',
    'hero.trust2': 'Гарантия результата',
    'hero.trust3': 'Небольшие интерактивные группы',
    'hero.stats.students': 'Успешных студентов',
    'hero.stats.successRate': 'Успешность экзаменов',
    'hero.stats.teachers': 'Опытных преподавателей',
    'hero.stats.courses': 'Специализированных курсов',
    'hero.stats.excellence': 'Академическое превосходство',
    'hero.card.title': 'Достижения студентов',
    'hero.card.subtitle': 'Официальная база результатов',
    'hero.card.badge': 'Проверено в реальном времени',
    'hero.card.video': 'Смотреть видео-тур по кампусу',
    'hero.noResults.title': 'Топовые результаты экзаменов и поступления',
    'hero.noResults.desc': 'Записи об успехах студентов хранятся в базе данных Supabase.',
    'about.tag': 'О iStudy Academy',
    'about.title': 'Там, где амбиции встречаются с',
    'about.titleHighlight': 'мировым наставничеством.',
    'about.subtitle': 'Мы не просто проводим курсы — мы строим понятные пути к поступлению в лучшие университеты и карьерным возможностям.',
    'about.tabs.story': 'История',
    'about.tabs.mission': 'Миссия',
    'about.tabs.vision': 'Видение',
    'about.tabs.methodology': 'Методика',
    'about.story.title': 'Основано на качестве и реальных результатах',
    'about.story.description': 'iStudy Academy была создана с одной целью — давать мировое образование без компромиссов. За последние 3+ года мы выросли в многопрофильную академию, выпустившую тысячи студентов, которые учатся в лучших вузах и работают в ведущих компаниях.',
    'about.story.point1': 'Собственная методика, повышающая баллы, протестированная на 5000+ кандидатах',
    'about.story.point2': 'Официальный центр пробных тестов, имитирующий реальный стресс экзамена',
    'about.story.point3': 'Заведующие отделами с сертификатами Cambridge CELTA и DELTA',
    'about.mission.title': 'Помогаем студентам достигать глобальных высот',
    'about.mission.description': 'Наша миссия — дать каждому амбициозному ученику сильные международные квалификации (IELTS, CEFR, SAT) и будущие цифровые навыки (Software Engineering, UI/UX, SMM), открывающие путь к грантам и карьерным возможностям.',
    'about.mission.point1': 'Доступ к высоким баллам IELTS и SAT',
    'about.mission.point2': 'Развитие критического мышления, уверенности в речи и беглости',
    'about.mission.point3': 'Полная прозрачность для родителей и кандидатов',
    'about.vision.title': 'Стать №1 в Центральной Азии по подготовке и цифровым технологиям',
    'about.vision.description': 'Мы видим будущее, в котором iStudy Academy станет эталоном образовательного превосходства в регионе и будет глобально признана за отправку тысяч студентов в ведущие университеты.',
    'about.vision.point1': 'Постоянное внедрение ИИ в диагностику учеников',
    'about.vision.point2': 'Расширение партнёрств с зарубежными вузами',
    'about.vision.point3': 'Создание сети выпускников-лидеров и инновационеров',
    'about.methodology.title': '4-ступенчатая система обучения iStudy',
    'about.methodology.description': 'В отличие от пассивных лекций, наша методика строится на активной практике: 40% — основы, 30% — интенсивные упражнения, 20% — пробные тесты и 10% — индивидуальная обратная связь.',
    'about.methodology.point1': 'Небольшие группы до 10-12 учеников',
    'about.methodology.point2': 'Анализ ошибок после каждого теста',
    'about.methodology.point3': 'Ежедневные разговорные клубы и проекты по программированию',
    'about.card.title': 'Современный кампус iStudy Academy',
    'about.card.subtitle': 'Современные классы и лаборатории IELTS.',
    'about.card.badge': 'Видео-тур',
    'about.card.branch': 'Откройте наш главный кампус',
    'about.card.branchSubtitle': 'Центральный филиал • Тур по кампусу',
    'about.feature1.title': 'Сертифицировано Cambridge',
    'about.feature1.subtitle': 'Лицензированный стандарт',
    'about.feature2.title': 'Гарантия результата',
    'about.feature2.subtitle': 'Цель Band 7.0+',
    'why.tag': 'Преимущества iStudy',
    'why.title': 'Почему лучшие студенты выбирают',
    'why.titleHighlight': 'iStudy Academy.',
    'why.subtitle': 'Каждая деталь нашей академической системы направлена на рост баллов, уверенность и реальные результаты.',
    'why.feature.standard': 'Базовая функция',
    'courses.tag': 'Академические программы',
    'courses.title': 'Откройте премиальные',
    'courses.titleHighlight': 'образовательные курсы.',
    'courses.subtitle': 'Реальные курсы, напрямую подключённые к базе данных Supabase.',
    'courses.filter.all': 'Все курсы',
    'courses.filter.english': 'Английский и экзамены (IELTS/CEFR)',
    'courses.filter.prep': 'SAT и математика',
    'courses.filter.tech': 'Программирование и ИИ',
    'courses.filter.design': 'Графический дизайн и SMM',
    'courses.search': 'Искать курсы...',
    'courses.empty.title': 'В базе Supabase нет курсов',
    'courses.empty.desc': 'Все тестовые данные удалены. Создавайте и управляйте курсами через админ-панель.',
    'courses.empty.admin': 'В админ-панель',
    'courses.empty.enroll': 'Быстрая запись',
    'courses.noMatch.title': 'Под ваш фильтр курсы не подходят',
    'courses.noMatch.desc': 'Попробуйте сбросить поиск или выбрать другую категорию.',
    'courses.reset': 'Сбросить фильтры',
    'courses.card.level': 'Уровень',
    'courses.card.learnMore': 'Подробнее',
    'courses.card.enroll': 'Записаться',
    'teachers.tag': 'Мировые наставники',
    'teachers.title': 'Учитесь у сертифицированных',
    'teachers.titleHighlight': 'экзаменаторов и экспертов.',
    'teachers.subtitle': 'Наши преподаватели — носители языка, обладатели Band 9.0 и опытные разработчики.',
    'teachers.credentials': 'Сертификаты и квалификация:',
    'teachers.book': 'Записаться на консультацию',
    'teachers.exp': 'Стаж',
    'results.tag': 'Зал славы студентов',
    'results.title': 'Реальные результаты студентов и',
    'results.titleHighlight': 'поступления в университеты.',
    'results.subtitle': 'Посмотрите, как наши ученики повысили баллы и получили гранты.',
    'results.growth': 'Рост балла:',
    'gallery.tag': 'Кампус и события',
    'gallery.title': 'Жизнь в iStudy',
    'gallery.titleHighlight': 'галерея академии.',
    'gallery.subtitle': 'Посмотрите на наши современные классы, выпускные церемонии и активные клубы.',
    'gallery.filter.all': 'Все фото и видео',
    'gallery.filter.classrooms': 'Классы',
    'gallery.filter.graduation': 'Выпуск',
    'gallery.filter.events': 'События и мастер-классы',
    'gallery.filter.activities': 'Студенческая жизнь',
    'testimonials.tag': 'Отзывы студентов и родителей',
    'testimonials.title': 'Любимы более чем',
    'testimonials.titleHighlight': '5000+ семей.',
    'testimonials.subtitle': 'Читайте подлинные отзывы тех, кто достиг Band 8.5+ и родителей, наблюдавших за ростом своих детей.',
    'testimonials.filter.all': 'Все отзывы',
    'testimonials.filter.student': 'Отзывы студентов',
    'testimonials.filter.parent': 'Отзывы родителей',
    'testimonials.filter.alumni': 'Отзывы выпускников',
    'news.tag': 'Последние новости и события',
    'news.title': 'Будьте в курсе',
    'news.titleHighlight': 'новостей iStudy Academy.',
    'news.subtitle': 'Узнавайте о бесплатных пробных экзаменах, вебинарах и мастер-классах.',
    'news.readMore': 'Читать полностью',
    'faq.tag': 'Часто задаваемые вопросы',
    'faq.title': 'Есть вопросы?',
    'faq.titleHighlight': 'У нас есть ответы.',
    'faq.subtitle': 'Найдите всё, что нужно знать о тестах, расписании и гарантиях результатов.',
    'faq.search': 'Искать вопросы...',
    'faq.category.all': 'Все',
    'faq.category.general': 'Общие',
    'faq.category.courses': 'Курсы',
    'faq.category.payments': 'Оплата',
    'faq.category.schedule': 'Расписание',
    'contact.tag': 'Контакты и филиалы',
    'contact.title': 'Посетите наши кампусы или',
    'contact.titleHighlight': 'запросите бесплатную консультацию.',
    'contact.subtitle': 'Наш офис приёма открыт с понедельника по субботу. Заполните форму ниже или зайдите в один из 3 центральных кампусов.',
    'contact.branchTitle': 'Выберите филиал академии:',
    'contact.activeBranch': 'Активный филиал',
    'contact.socialTitle': 'Следите за iStudy:',
    'contact.formTitle': 'Напишите нам / Запишитесь',
    'contact.formSubtitle': 'Оставьте свои данные, и менеджер свяжется с вами в течение 15 минут!',
    'contact.name': 'Полное имя *',
    'contact.phone': 'Номер телефона *',
    'contact.course': 'Выберите курс',
    'contact.branch': 'Выберите филиал',
    'contact.message': 'Сообщение или вопросы (необязательно)',
    'contact.messagePlaceholder': 'Расскажите нам о целевом балле или удобном расписании...',
    'contact.social.telegram': 'Telegram',
    'contact.social.instagram': 'Instagram',
    'contact.social.facebook': 'Facebook',
    'contact.social.linkedin': 'LinkedIn',
    'contact.exampleName': 'напр., Иван Иванов',
    'contact.submit': 'Отправить заявку и получить консультацию',
    'contact.sending': 'Отправка заявки...',
    'footer.subscribeTitle': 'Подписывайтесь на бесплатные уведомления о пробных экзаменах',
    'footer.subscribeSubtitle': 'Получайте еженедельные словари IELTS и новости о стипендиях прямо на почту.',
    'footer.emailPlaceholder': 'Введите ваш email...',
    'footer.subscribe': 'Подписаться',
    'footer.quickLinks': 'Быстрые ссылки',
    'footer.aboutUs': 'О нас',
    'footer.allCourses': 'Все курсы',
    'footer.faculty': 'Преподаватели',
    'footer.studentResults': 'Результаты студентов',
    'footer.photoGallery': 'Фотогалерея',
    'footer.newsEvents': 'Новости и события',
    'footer.programs': 'Академические программы',
    'footer.campuses': 'Филиалы',
    'footer.privacy': 'Политика конфиденциальности и условия',
    'footer.backTop': 'Наверх',
    'footer.copyright': '© 2026 iStudy Academy. Все права защищены. Международный лицензированный образовательный центр.',
    'toast.enrollSuccess.title': 'Регистрация подтверждена!',
    'toast.enrollSuccess.desc': 'Спасибо {name}. Место на курс «{course}» зарезервировано! Ref: {ref}',
    'toast.contactSuccess.title': 'Заявка получена!',
    'toast.contactSuccess.desc': 'Здравствуйте, {name}. Наш менеджер перезвонит на {phone} в течение 15 минут.',
    'toast.subscribeSuccess.title': 'Вы подписались на рассылку iStudy!',
    'toast.subscribeSuccess.desc': 'Мы отправили ссылку подтверждения на {email}. Проверьте почту для бесплатных материалов по IELTS.',
    'toast.consultation.title': 'Запрос на консультацию с {teacher}',
    'toast.consultation.desc': 'Заполните форму ниже или звоните +998 (71) 200-77-88, чтобы записаться.',
    'toast.error.title': 'Не удалось отправить заявку',
    'toast.error.desc': 'Не удалось сохранить сообщение. Попробуйте позже.',
    'toast.subscribeError.title': 'Не удалось подписаться',
    'toast.subscribeError.desc': 'Не удалось оформить подписку. Попробуйте позже.',
    'why.feature1.title': 'Опытные преподаватели',
    'why.feature1.desc': 'Преподаватели с сертификатами Cambridge CELTA и DELTA, носители языка и обладатели IELTS Band 9.0.',
    'why.feature2.title': 'Современные классы',
    'why.feature2.desc': 'Интерактивные доски, лаборатории iMac, удобные кресла и тихие зоны для обучения.',
    'why.feature3.title': 'Международная программа',
    'why.feature3.desc': 'Официально лицензированные программы Cambridge, Oxford и SAT по цифровой подготовке.',
    'why.feature4.title': 'Небольшие группы',
    'why.feature4.desc': 'Максимум 10-12 учеников в группе для персональной обратной связи и времени для разговорной практики.',
    'why.feature5.title': 'Гибкий график',
    'why.feature5.desc': 'Выбирайте утренние, дневные, вечерние или интенсивные выходные занятия.',
    'why.feature6.title': 'Доступные цены',
    'why.feature6.desc': 'Прозрачные цены без скрытых платежей, скидки для братьев и сестёр и выгодные тарифы при оплате за 3 месяца.',
    'why.feature7.title': 'Официальные сертификаты',
    'why.feature7.desc': 'Выпускные дипломы с QR-проверкой, признанные работодателями и вузами.',
    'why.feature8.title': 'Помощь с поступлением и карьерой',
    'why.feature8.desc': 'Отдельные консультанты по Common App, мотивационным письмам и стипендиям.',
    'common.themeLight': 'Светлая',
    'common.themeDark': 'Тёмная',
    'common.language': 'Язык',
    'common.languageEn': 'English',
    'common.languageRu': 'Русский',
    'common.languageUz': 'O‘zbek',
    'common.selectLanguage': 'Выберите язык',
    'common.changeTheme': 'Тема',
  },
  uz: {
    'nav.home': 'Bosh sahifa',
    'nav.about': 'Biz haqimizda',
    'nav.courses': 'Kurslar',
    'nav.teachers': 'O‘qituvchilar',
    'nav.results': 'Natijalar',
    'nav.gallery': 'Galereya',
    'nav.news': 'Yangiliklar',
    'nav.testimonials': 'Sharhlar',
    'nav.faq': 'FAQ',
    'nav.contact': 'Bog‘lanish',
    'nav.levelTest': 'Daraja testi',
    'nav.enroll': 'Ro‘yxatdan o‘tish',
    'nav.admin': 'Admin panel',
    'nav.mobileAdmin': 'Admin',
    'nav.mobileLevelTest': 'Bepul daraja testini topshirish',
    'nav.mobileEnroll': 'Ro‘yxatdan o‘tish',
    'nav.mobileAdminGo': 'Admin panelga o‘tish',
    'hero.tag': 'Premier xalqaro ta’lim markazi',
    'hero.title': 'Kelajagingizni shu bilan yarating',
    'hero.titleHighlight': 'iStudy Academy.',
    'hero.subtitle': 'Cambridge sertifikatli native o‘qituvchilar va yuqori reytingli imtihon mutaxassislar bilan ingliz tili, IELTS, CEFR, SAT hamda texnologiya va dizayn ko‘nikmalarini o‘rganing.',
    'hero.enroll': 'Ro‘yxatdan o‘tish',
    'hero.levelTest': 'Testni topshirish',
    'hero.trust1': 'Cambridge standarti',
    'hero.trust2': 'Natija kafolati',
    'hero.trust3': 'Kichik interaktiv guruhlar',
    'hero.stats.students': 'Muvaffaqiyatli talabalar',
    'hero.stats.successRate': 'Imtihon muvaffaqiyati',
    'hero.stats.teachers': 'Mutaxassis o‘qituvchilar',
    'hero.stats.courses': 'Maxsus kurslar',
    'hero.stats.excellence': 'Akademik mukammallik',
    'hero.card.title': 'Talabalar yutuqlari',
    'hero.card.subtitle': 'Rasmiy natija bazasi',
    'hero.card.badge': 'Jonli tasdiqlangan',
    'hero.card.video': 'Akademiya kampusiga video sayohat',
    'hero.noResults.title': 'Imtihon natijalari va universitet qabul natijalari',
    'hero.noResults.desc': 'Talabalar yutuqlari yozuvlari Supabase ma’lumotlar bazasida saqlanadi.',
    'about.tag': 'iStudy Academy haqida',
    'about.title': 'Ambitsiyalar uchrashadigan joy',
    'about.titleHighlight': 'Dunyo darajasidagi murabbiylik.',
    'about.subtitle': 'Biz faqat kurs o‘qitmaymiz; biz yuqori universitetlarga va yuqori maoshli kasblarga olib boradigan aniq yo‘llarni yaratamiz.',
    'about.tabs.story': 'Tarix',
    'about.tabs.mission': 'Missiya',
    'about.tabs.vision': 'Vizyon',
    'about.tabs.methodology': 'Metodika',
    'about.story.title': 'Mukammallik va haqiqiy natijalar asosida',
    'about.story.description': 'iStudy Academy bitta maqsad bilan tashkil etilgan: kompromissiz dunyo darajasidagi ta’lim berish. So‘nggi 3+ yil ichida biz minglab bitiruvchilarni tarbiyalagan ko‘p tarmoqli akademiyaga aylandik.',
    'about.story.point1': '5000+ nomzodlar ustida sinovdan o‘tilgan maxsus ball oshirish metodikasi',
    'about.story.point2': 'Real imtihon stressini taqlid qiluvchi rasmiy test markazi',
    'about.story.point3': 'Cambridge CELTA va DELTA sertifikatli bo‘lim rahbarlari',
    'about.mission.title': 'Talabalarni global cho‘qqilarga olib chiqish',
    'about.mission.description': 'Bizning missiyamiz har bir ambitsiyali o‘quvchini yuqori qiymatli xalqaro malakalar (IELTS, CEFR, SAT) va kelajak uchun zarur bo‘lgan raqamli ko‘nikmalar (Software Engineering, UI/UX, SMM) bilan qurollantirishdir.',
    'about.mission.point1': 'Yuqori IELTS va SAT ballariga kirish imkoniyatini kengaytirish',
    'about.mission.point2': 'Tanqidiy fikrlash, nutqiy ishonch va ravonlikni rivojlantirish',
    'about.mission.point3': 'Ota-onalar va nomzodlar uchun 100% shaffof kuzatuv',
    'about.vision.title': 'Markaziy Osiyoda #1 tayyorgarlik va texnologiya darvozasi bo‘lish',
    'about.vision.description': 'Biz kelajakda iStudy Academy mintaqada ta’lim mukammalligining benchmarkiga aylanishini va har yili minglab talabalarni yetakchi universitetlarga yuborishini ko‘ramiz.',
    'about.vision.point1': 'Talabalar diagnostikasida sun’iy intellektni muntazam joriy etish',
    'about.vision.point2': 'Chet ellik universitetlar bilan strategik hamkorliklarni kengaytirish',
    'about.vision.point3': 'Yetakchilar va innovatorlardan iborat abituriyentlar tarmog‘ini yaratish',
    'about.methodology.title': 'iStudy ta’limining 4 ta ustuni',
    'about.methodology.description': 'Oddiy passiv darslardan farqli o‘laroq, bizning metodikamiz faol ishlab chiqarishga asoslangan: 40% konsept asoslari, 30% real vaqtli mashqlar, 20% mock imtihonlari va 10% 1-on-1 ekspert fikri.',
    'about.methodology.point1': '10-12 nafar talaba bilan kichik interaktiv guruhlar',
    'about.methodology.point2': 'Har bir testdan keyin zaif jihatlarni tahlil qilish',
    'about.methodology.point3': 'Kundalik suhbat klublari va loyihaviy dasturlash sharhlari',
    'about.card.title': 'iStudy Academy zamonaviy kampusi',
    'about.card.subtitle': 'Yuqori texnologiyali sinflar va IELTS test laboratoriyalari.',
    'about.card.badge': 'Video sayohat',
    'about.card.branch': 'Asosiy kampusimizni ko‘ring',
    'about.card.branchSubtitle': 'Markaziy filial • Kampus turi',
    'about.feature1.title': 'Cambridge sertifikatli',
    'about.feature1.subtitle': 'Litsenziyalangan standart',
    'about.feature2.title': 'Natija kafolati',
    'about.feature2.subtitle': 'Band 7.0+ maqsad',
    'why.tag': 'iStudy afzalliklari',
    'why.title': 'Nega yuqori natijalarga erishgan talabalar tanlaydi',
    'why.titleHighlight': 'iStudy Academy.',
    'why.subtitle': 'Bizning akademik tizimimizning har bir tafsiloti ballaringizni oshirish, ishonchni mustahkamlash va real natijalarni ta’minlash uchun ishlab chiqilgan.',
    'why.feature.standard': 'Standart xususiyat',
    'courses.tag': 'Akademik dasturlar',
    'courses.title': 'Premium',
    'courses.titleHighlight': 'ta’lim kurslarini o‘rganing.',
    'courses.subtitle': 'Supabase bulut ma’lumotlar bazasiga to‘g‘ridan-to‘g‘ri ulangan haqiqiy kurslar.',
    'courses.filter.all': 'Barcha kurslar',
    'courses.filter.english': 'Ingliz tili va imtihonlar (IELTS/CEFR)',
    'courses.filter.prep': 'SAT va matematika tayyorgarligi',
    'courses.filter.tech': 'Dasturlash va AI',
    'courses.filter.design': 'Grafik dizayn va SMM',
    'courses.search': 'Kurslarni qidirish...',
    'courses.empty.title': 'Supabase ma’lumotlar bazasida kurs yo‘q',
    'courses.empty.desc': 'Barcha mock ma’lumotlar olib tashlandi. Admin panel orqali jonli kurslarni yarating va boshqaring.',
    'courses.empty.admin': 'Admin panelga o‘tish',
    'courses.empty.enroll': 'Tez ro‘yxatdan o‘tish',
    'courses.noMatch.title': 'Sizning filtringizga hech qanday kurs mos kelmadi',
    'courses.noMatch.desc': 'Qidiruv so‘rovini tozalash yoki boshqa toifani tanlashga harakat qiling.',
    'courses.reset': 'Filtrlarni tiklash',
    'courses.card.level': 'Daraja',
    'courses.card.learnMore': 'Batafsil',
    'courses.card.enroll': 'Ro‘yxatdan o‘tish',
    'teachers.tag': 'Dunyo darajasidagi murabbiylar',
    'teachers.title': 'Sertifikatlangan',
    'teachers.titleHighlight': 'eksaminatorlar va mutaxassislardan o‘rganing.',
    'teachers.subtitle': 'Bizning facultyamizda Cambridge CELTA/DELTA native o‘qituvchilari, Band 9.0 egasi va tajribali ishlab chiqarish mutaxassislari bor.',
    'teachers.credentials': 'Sertifikatlar va malakalar:',
    'teachers.book': 'Konsultatsiyaga yozilish',
    'teachers.exp': 'Tajriba',
    'results.tag': 'Talabalar shon-sharaf zali',
    'results.title': 'Haqiqiy talabalar natijalari va',
    'results.titleHighlight': 'universitetga qabul.',
    'results.subtitle': 'Bizning bitiruvchilarimiz qanday qilib ballarini oshirib, global stipendiyalarni qo‘lga kiritganini ko‘ring.',
    'results.growth': 'Ball o‘sishi:',
    'gallery.tag': 'Kampus va tadbirlar',
    'gallery.title': 'iStudyda hayot',
    'gallery.titleHighlight': 'akademiya galereyasi.',
    'gallery.subtitle': 'Yuqori texnologiyali o‘quv markazlari, yil yakunlari va faol suhbat klublari haqida ko‘ring.',
    'gallery.filter.all': 'Barcha fotosuratlar va videolar',
    'gallery.filter.classrooms': 'Sinfxonalar',
    'gallery.filter.graduation': 'Bitiruv',
    'gallery.filter.events': 'Tadbirlar va master-klasslar',
    'gallery.filter.activities': 'Talabalar hayoti',
    'testimonials.tag': 'Talabalar va ota-onalar fikrlari',
    'testimonials.title': '5000+ oila tomonidan',
    'testimonials.titleHighlight': 'sevimli.',
    'testimonials.subtitle': 'Band 8.5+ ga erishgan talabalar va farzandlarining rivojlanishini kuzatgan ota-onalarning ishonchli sharhlarini o‘qing.',
    'testimonials.filter.all': 'Barcha sharhlar',
    'testimonials.filter.student': 'Talaba sharhlari',
    'testimonials.filter.parent': 'Ota-ona sharhlari',
    'testimonials.filter.alumni': 'Bitiruvchi sharhlari',
    'news.tag': 'So‘nggi yangiliklar va tadbirlar',
    'news.title': 'Yangiliklardan xabardor bo‘ling',
    'news.titleHighlight': 'iStudy Academy yangiliklari.',
    'news.subtitle': 'Bepul mock imtihonlar, universitet qabuliga oid vebinarlar va akademik seminarlarni ko‘ring.',
    'news.readMore': 'To‘liq o‘qish',
    'faq.tag': 'Tez-tez so‘raladigan savollar',
    'faq.title': 'Savollaringiz bormi?',
    'faq.titleHighlight': 'Bizda javoblar bor.',
    'faq.subtitle': 'Joylashtirish testi, jadval va natija kafolati haqida kerak bo‘lgan hamma narsani toping.',
    'faq.search': 'FAQ savollarini qidirish...',
    'faq.category.all': 'Hammasi',
    'faq.category.general': 'Umumiy',
    'faq.category.courses': 'Kurslar',
    'faq.category.payments': 'To‘lovlar',
    'faq.category.schedule': 'Jadval',
    'contact.tag': 'Kontaktlar va filiallar',
    'contact.title': 'Kampuslarimizga tashrif buyuring yoki',
    'contact.titleHighlight': 'bepul konsultatsiya so‘rang.',
    'contact.subtitle': 'Bizning qabul bo‘limi dushanbadan shanbagacha ochiq. Quyidagi formani to‘ldiring yoki 3 ta markaziy kampusdan biriga tashrif buyuring.',
    'contact.branchTitle': 'Akademiya filialini tanlang:',
    'contact.activeBranch': 'Faol filial',
    'contact.socialTitle': 'iStudy rasmiy sahifalarini kuzatib boring:',
    'contact.formTitle': 'Bizga xabar yuboring / Ro‘yxatdan o‘ting',
    'contact.formSubtitle': 'Ma’lumotlaringizni qoldiring, ta’lim menejeri 15 daqiqada sizga qaytib qo‘ng‘iroq qiladi!',
    'contact.name': 'To‘liq ism *',
    'contact.phone': 'Telefon raqami *',
    'contact.course': 'Kursni tanlang',
    'contact.branch': 'Filialni tanlang',
    'contact.message': 'Xabar yoki savollar (ixtiyoriy)',
    'contact.messagePlaceholder': 'Maqsadli balingiz yoki qulay jadval haqida ayting...',
    'contact.social.telegram': 'Telegram',
    'contact.social.instagram': 'Instagram',
    'contact.social.facebook': 'Facebook',
    'contact.social.linkedin': 'LinkedIn',
    'contact.exampleName': 'masalan, John Doe',
    'contact.submit': 'So‘rov yuborish va konsultatsiya olish',
    'contact.sending': 'So‘rov yuborilmoqda...',
    'footer.subscribeTitle': 'Bepul mock imtihon ogohlantirishlari uchun obuna bo‘ling',
    'footer.subscribeSubtitle': 'Haftalik IELTS lug‘atlari va stipendiya yangiliklarini elektron pochtangizga oling.',
    'footer.emailPlaceholder': 'Emailingizni kiriting...',
    'footer.subscribe': 'Obuna bo‘lish',
    'footer.quickLinks': 'Tez havolalar',
    'footer.aboutUs': 'Biz haqimizda',
    'footer.allCourses': 'Barcha kurslar',
    'footer.faculty': 'O‘qituvchilar va murabbiylar',
    'footer.studentResults': 'Talabalar natijalari',
    'footer.photoGallery': 'Foto galereya',
    'footer.newsEvents': 'Yangiliklar va tadbirlar',
    'footer.programs': 'Akademik dasturlar',
    'footer.campuses': 'Filiallar',
    'footer.privacy': 'Maxfiylik siyosati va shartlar',
    'footer.backTop': 'Yuqoriga',
    'footer.copyright': '© 2026 iStudy Academy. Barcha huquqlar himoyalangan. Xalqaro litsenziyalangan ta’lim markazi.',
    'toast.enrollSuccess.title': 'Ro‘yxatdan o‘tish tasdiqlandi!',
    'toast.enrollSuccess.desc': 'Rahmat {name}. «{course}» kursi uchun joy band qilingan! Ref: {ref}',
    'toast.contactSuccess.title': 'So‘rov qabul qilindi!',
    'toast.contactSuccess.desc': 'Hurmatli {name}, menejer {phone} raqamiga 15 daqiqadan ichida qaytib qo‘ng‘iroq qiladi.',
    'toast.subscribeSuccess.title': 'iStudy axborot byulleteniga obuna bo‘ldingiz!',
    'toast.subscribeSuccess.desc': 'Biz {email} manziliga tasdiqlash havolasini yubordik. Bepul IELTS materiallari uchun pochta quting.',
    'toast.consultation.title': '{teacher} bilan konsultatsiya so‘rovi',
    'toast.consultation.desc': 'Quyidagi formani to‘ldiring yoki rejalashtirish uchun +998 (71) 200-77-88 raqamiga qo‘ng‘iroq qiling.',
    'toast.error.title': 'So‘rov yuborilmadi',
    'toast.error.desc': 'Xabarni hozir saqlab bo‘lmadi. Iltimos, keyinroq urinib ko‘ring.',
    'toast.subscribeError.title': 'Obuna bo‘lish amalga oshmadi',
    'toast.subscribeError.desc': 'Elektron pochta obunasini hozirda ro‘yxatdan o‘tkazib bo‘lmadi. Iltimos, keyinroq urinib ko‘ring.',
    'why.feature1.title': 'Tajribali o‘qituvchilar',
    'why.feature1.desc': 'Cambridge CELTA va DELTA sertifikatiga ega o‘qituvchilar, native speakers va IELTS Band 9.0 egasi mutaxassislar.',
    'why.feature2.title': 'Zamonaviy sinflar',
    'why.feature2.desc': 'Interaktiv taxtalar, iMac texnologik laboratoriyalar, qulay ergonomik stullar va tinch o‘quv zonalari.',
    'why.feature3.title': 'Xalqaro ta’lim dasturi',
    'why.feature3.desc': 'Rasmiy litsenziyalangan Cambridge, Oxford va College Board SAT raqamli tayyorgarlik dasturlari.',
    'why.feature4.title': 'Kichik guruhlar',
    'why.feature4.desc': 'Har bir guruhda maksimal 10-12 nafar talaba, shaxsiy fikr-mulohaza va suhbat vaqti ta’minlanadi.',
    'why.feature5.title': 'Moslashuvchan jadval',
    'why.feature5.desc': 'Ertalabki, tushki, kechki yoki dam olish kunlari intensiv mashg‘ulotlardan birini tanlang.',
    'why.feature6.title': 'Arzon narxlar',
    'why.feature6.desc': 'Yashirin to‘lovlarsiz ochiq narxlar, aka-uka singillar uchun chegirmalar va 3 oyga oldindan to‘lovda qulay tariflar.',
    'why.feature7.title': 'Rasmiy sertifikatlar',
    'why.feature7.desc': 'QR-verifikatsiyaga ega bitiruv diplomlari, ish beruvchilar va muassasalar tomonidan tan olingan.',
    'why.feature8.title': 'Kirish va martaba bo‘yicha yordam',
    'why.feature8.desc': 'Common App, motivatsion xatlar va stipendiyalar bo‘yicha alohida maslahatchilar.',
    'common.themeLight': 'Yorug‘',
    'common.themeDark': 'Qorong‘i',
    'common.language': 'Til',
    'common.languageEn': 'English',
    'common.languageRu': 'Русский',
    'common.languageUz': 'O‘zbek',
    'common.selectLanguage': 'Tilni tanlang',
    'common.changeTheme': 'Mavzu',
  },
};

const getInitialTheme = (): ThemeMode => {
  if (typeof window === 'undefined') return 'light';
  const saved = window.localStorage.getItem('istudy-theme');
  return saved === 'dark' ? 'dark' : 'light';
};

const getInitialLanguage = (): AppLanguage => {
  if (typeof window === 'undefined') return 'en';
  const saved = window.localStorage.getItem('istudy-language') as AppLanguage | null;
  return saved && ['en', 'ru', 'uz'].includes(saved) ? saved : 'en';
};

export const ThemeLanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [theme, setThemeState] = useState<ThemeMode>(getInitialTheme);
  const [language, setLanguageState] = useState<AppLanguage>(getInitialLanguage);

  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark');
    document.documentElement.setAttribute('data-theme', theme);
    window.localStorage.setItem('istudy-theme', theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = language;
    window.localStorage.setItem('istudy-language', language);
  }, [language]);

  const setTheme = (nextTheme: ThemeMode) => setThemeState(nextTheme);
  const setLanguage = (nextLanguage: AppLanguage) => setLanguageState(nextLanguage);

  const t = (key: string) => {
    const fallback = translations.en[key] || key;
    return translations[language]?.[key] || fallback;
  };

  const value = useMemo<ThemeLanguageContextValue>(() => ({
    theme,
    language,
    setTheme,
    setLanguage,
    t,
  }), [theme, language]);

  return <ThemeLanguageContext.Provider value={value}>{children}</ThemeLanguageContext.Provider>;
};

export const useThemeLanguage = () => {
  const context = useContext(ThemeLanguageContext);
  if (!context) {
    throw new Error('useThemeLanguage must be used within ThemeLanguageProvider');
  }
  return context;
};
